config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do  
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  resources :beaters
  devise_for :users

  root 'beaters#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beater.rb
class Beater < ApplicationRecord
  include HTTParty
  open_timeout 5 # default 10
  read_timeout 5 # default 10

  # StatusChannel.broadcast_to beater.user, beater
  belongs_to :user

  enum provider: %i[heroku]
  enum status: %i[offline online]
  
  validates :status, presence: true
  validates_format_of :url, with: URI::regexp(%w(http https))
  validates :url, uniqueness: true, presence: true

  after_update_commit :update_client_status, if: :saved_change_to_status?

  def ping
    status = :offline
    status = :online if ping_success?
  ensure
    update(status: status)
  end

  private

  def ping_success?
    self.class.get(url).code == 200
  end

  def update_client_status
    StatusChannel.broadcast_to user, self
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :beaters, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beaters_controller.rb
class BeatersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_beater, only: [:show, :edit, :update, :destroy]

  # GET /beaters
  # GET /beaters.json
  def index
    @beaters = current_user.beaters
  end

  # GET /beaters/1
  # GET /beaters/1.json
  def show
  end

  # GET /beaters/new
  def new
    @beater = current_user.beaters.new
  end

  # GET /beaters/1/edit
  def edit
  end

  # POST /beaters
  # POST /beaters.json
  def create
    @beater = current_user.beaters.new(beater_params)
    respond_to do |format|
      if @beater.save
        format.html { redirect_to @beater, notice: 'Beater was successfully created.' }
        format.json { render :show, status: :created, location: @beater }
      else
        format.html { render :new }
        format.json { render json: @beater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beaters/1
  # PATCH/PUT /beaters/1.json
  def update
    respond_to do |format|
      if @beater.update(beater_params)
        format.html { redirect_to @beater, notice: 'Beater was successfully updated.' }
        format.json { render :show, status: :ok, location: @beater }
      else
        format.html { render :edit }
        format.json { render json: @beater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beaters/1
  # DELETE /beaters/1.json
  def destroy
    @beater.destroy
    respond_to do |format|
      format.html { redirect_to beaters_url, notice: 'Beater was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beater
      @beater = current_user.beaters.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beater_params
      params.require(:beater).permit(:name, :provider, :url)
    end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  before_action :authenticate_user!

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = WakeupSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beaters_helper.rb
module BeatersHelper
end

app/views/beaters/_form.html.haml
= form_with(model: beater, local: true) do |form|
  - if beater.errors.any?
    #error_explanation
      %h2
        = pluralize(beater.errors.count, "error")
        prohibited this beater from being saved:
      %ul
        - beater.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :provider
    = form.select :provider, options_for_select(Beater.providers.keys)
  .field
    = form.label :url
    = form.text_field :url
  .actions
    = form.submit

app/views/beaters/edit.html.haml
%h1 Editing Beater
= render 'form', beater: @beater
= link_to 'Show', @beater
|
= link_to 'Back', beaters_path

app/views/beaters/index.html.haml
%h1 Beaters
.table-responsive
  %table.table
    %thead.thead-dark
      %tr
        %th Name
        %th Provider
        %th Url
        %th Status
        %th{:colspan => "3"}
    %tbody
      - @beaters.each do |beater|
        %tr{id: "beater-#{beater.id}"}
          %td= beater.name
          %td= beater.provider
          %td= beater.url
          %td
            .btn{ class: "btn-#{beater.status == 'online' ? 'success' : 'danger'}" }
              = beater.status
          %td= link_to 'Show', beater
          %td= link_to 'Edit', edit_beater_path(beater)
          %td= link_to 'Destroy', beater, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Beater', new_beater_path

app/views/beaters/new.html.haml
%h1 New Beater
= render 'form', beater: @beater
= link_to 'Back', beaters_path

app/views/beaters/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @beater.name
%p
  %strong Provider:
  = @beater.provider
%p
  %strong Url:
  = @beater.url
%p
  %strong User:
  = @beater.user.email
= link_to 'Edit', edit_beater_path(@beater)
|
= link_to 'Back', beaters_path

app/views/layouts/_navigation.html.haml
.row.my-2
  - if current_user
    .col-sm-10.text-right.pt-2
      %p Hello, #{current_user.email}
    .col-sm-2.text-right
      = button_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger'

app/views/layouts/_notification.html.haml
.toast#notification{"aria-atomic": "true", "aria-live": "assertive", role: "alert", style: "position: absolute; top: 10px; right: 500px;"}
  .toast-header
    %strong.mr-auto Notification
    %small
    %button.ml-2.mb-1.close{"aria-label" => "Close", "data-dismiss" => "toast", :type => "button"}
      %span{"aria-hidden" => "true"} ×
  .toast-body
    = notice
    = alert

:javascript
  var notification = "#{notice}" || "#{alert}";
  if(notification) {
    $('#notification').css("right", "10px")
    $('#notification').toast({ delay: 5000 })
    $('#notification').toast('show')
  }

app/views/layouts/_toast.html.haml
%div{"aria-atomic" => "true", "aria-live" => "polite", :style => "position: absolute; top: 10px; right: 10px; min-height: 200px;"}
  .toast-container.d-flex.justify-content-end.align-items-end.flex-column

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    %meta{name: 'theme-color', content: '#343A40'}

    %title Wakeup
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link(rel="manifest" href="/manifest.json")/
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
  %body
    .container
      = render 'layouts/toast'
      = render 'layouts/navigation'
      = yield
    %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}
    = render 'layouts/notification'
    